project:
  type: website

website:
  title: "Sea Ice @ Alaska"

  sidebar:
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/polarwatch
        text: "PolarWatch Repository"
      - icon: globe
        href: https://polarwatch.noaa.gov
        text: "PolarWatch Website"

    contents:
      - href: arctic.qmd
        text: "Alaskan Arctic"
      - href: ebering.qmd
        text: "Eastern Bering"
      - href: nbering.qmd
        text: "Northern Bering"
      - href: https://shinyfin.psmfc.org/ak-sst-mhw/
        text: "ShinyFIN (SST)"
      - href: https:/polarwatch.noaa.gov
        text: "PolarWatch"
        

format:
  html:
    grid:
      # sidebar-width: 200px
      body-width: 1000px
    theme: flatly
    css: styles.css
    include-after-body: custom.js
    toc: true


exclude:
  - "_scripts/"

editor: visual

