name: Trigger Quarto Publish After Update

on:
  workflow_run:
    workflows: ["Update Daily Data"]
    types:
      - completed

jobs:
  trigger-quarto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Quarto Publish
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const ref = 'refs/heads/main'; // The branch you want to trigger
            const workflow_id = 'publish.yaml'; // The filename of the Quarto Publish workflow
            const response = await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref,
            });
            console.log(response);
