name: Update data Workflow

on:
  schedule:
    # Runs at 04:00 UTC every day
    # '0 4 * * *', '*/10 * * * *'
    - cron: '0 4 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Setup Miniconda
       uses: conda-incubator/setup-miniconda@v3
       with:
         python-version: 3.9
         activate-environment: seaice
         environment-file: environment.yaml
     
     - name: Run Python script
       run: |
          python scripts/update_daily_extent.py  # This script updates CSV files in data/
          
     - name: Commit and push if changes
       run: |
        git config --global user.email "sun.bak-hospital@noaa.gov"
        git config --global user.name "Sunny Hospital"
        git add data/*.csv
        git commit -m "Update CSV data" || echo "No changes to commit"
        git push

           
         
        
    
