# .github/worflows/publish.yaml

name: Update Data Direrctory

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
  schedule:
    # Runs at 05:00 UTC every day
    - cron: '0 5 * * *'
  workflow_dispatch:
    

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
     
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check out gh-pages branch
        run: |
          git fetch origin
          git checkout gh-pages
          git checkout main -- data/
          
      - name: Commit and push changes
        run: |
          git add data/
          git commit -m "Update data directory"
          git push origin gh-pages
